import type { Metadata } from "next";
import { Mouse_Memoirs } from "next/font/google";
import { Geist_Mono } from "next/font/google"; //
import "./globals.css";

const geistSans = Mouse_Memoirs({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
    ${geistSans.variable} ${geistMono.variable}
    antialiased min-w-full min-h-screen bg-no-repeat bg-cover bg-center
    bg-[url('/images/word-game-images/background-mobile.svg')]
    sm:bg-[url('/images/word-game-images/background-tablet.svg')]
    lg:bg-[url('/images/word-game-images/background-desktop.svg')]
  `}
      >
        {children}
      </body>
    </html>
  );
}
